### ISSUE TITLE
Device Type and Status not working

### ISSUE THREAD

**Issue by Hukuma1** [games-on-whales/wolfmanager#60]
<img width="1880" height="458" alt="Image" src="https://github.com/user-attachments/assets/a7f2f20b-b3a5-4b99-a202-048d285a21db" />

Status and device type do not seem to be working. Latest version. I also deleted all previous versions and tried to start anew. The status never changes to online. Just stays offline.

**Comment by salty2011** [comment]
Hey @Hukuma1 

The issue may have been due to me not publishing the release so no updates were sent out.

I've just done that now and you can check out the release here

https://github.com/games-on-whales/wolfmanager/releases/tag/202507.003

Device Type won't change, it's a dummy field I haven't done anything with yet. But the online/ offline / pause status along with pairing request should update.

Online status will only trigger once you have an app launched, I couldn't do based on listing apps in moonlight as no events for me to trigger the status change

**Comment by Hukuma1** [comment]
I thought I was going insane, but I don't think it's compiling the new version for Docker?

https://github.com/games-on-whales/wolfmanager/actions (the last one being released shows 3 days ago)

**Comment by salty2011** [comment]
hey @Hukuma1 

Sorry throught I replied... I realised my tagging was mismatched... I corrected it several weeks ago but didn't update you here. Have to tried pulling the latest version since?

**Comment by Hukuma1** [comment]
Heya! Yep. I tried just now. I still have the "latest" and it says "offline" even though I just connected to it and launched an app. Is there a way to see the version number in Wolfmanager?

```
docker images
ghcr.io/games-on-whales/wolfmanager/wolfmanager   latest                               900c09207740   2 weeks ago    1.74GB
```

**Comment by salty2011** [comment]
Hey @Hukuma1 

The latest release is **202508.001** 👉 [https://github.com/games-on-whales/wolfmanager/releases/tag/202508.001](https://github.com/games-on-whales/wolfmanager/releases/tag/202508.001) > posted wrong link before

To make sure you’re on the latest build could try one of the following:

```bash
# Pull the latest WolfManager image
docker pull ghcr.io/games-on-whales/wolfmanager:latest

# Or, if you prefer using a fixed tag (might be worth changing the tag to force over)
docker pull ghcr.io/games-on-whales/wolfmanager:202508.001

# Restart your container with the updated image
docker compose up -d
```

You can also check which version you’re currently running:

```bash
docker inspect ghcr.io/games-on-whales/wolfmanager:latest --format '{{ index .Config.Labels "org.opencontainers.image.version" }}'
```

Please give that a try and let us know if the issue still happens after updating 🙏

You raise a good point around checking the version of wolfmanager. Currently its really just the docker images, but ill raise a feature request to actually add something so its easily to determine in the future.

In the wolf discord another user who is using WolfManager is reporting status all working and I have been able to replicate your issue.

If this doesnt work, could I ask that you clear the log files, repeat the testing, and take screenshots. Then upload these to the this ticket along with the docker compose you are using for this. This is so I can gain better context for how it's setup and what might be happening.

**Comment by Hukuma1** [comment]
[wolfmanager-logs-2025-08-27T14_56_01.907Z.json](https://github.com/user-attachments/files/22010558/wolfmanager-logs-2025-08-27T14_56_01.907Z.json)

I can confirm I did pull the latest image, I used even the tagged one.

```
ghcr.io/games-on-whales/wolfmanager/wolfmanager   202508.001                           900c09207740   2 weeks ago    1.74GB
```

I started fresh, deleted all configs and re-pulled the image.

Everything seems to work, except the last seen is not being updated nor online/offline status it seems.

```
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    container_name: wolf
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=$CONFIG/wolf
      #   - WOLF_LOG_LEVEL=DEBUG
      - WOLF_SOCKET_PATH=/etc/wolf/wolf.sock
    volumes:
      - $CONFIG/wolf/:/etc/wolf:rw
      - $CONFIG/wolf/:$CONFIG/wolf/
      - $CONFIG/wolf/cfg:/etc/wolf/cfg
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    device_cgroup_rules:
      - c 13:* rmw
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    network_mode: host
    restart: unless-stopped
  wolfmanager:
    image: ghcr.io/games-on-whales/wolfmanager/wolfmanager:202508.001
    container_name: wolfmanager
    ports:
      - 3006:3000
    network_mode: bridge
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://192.168.1.4:3006
    volumes:
      - $CONFIG/wolf:/var/run/wolf # Mount Wolf socket
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - $CONFIG/wolfmanager:/app/config # Persist config directory
    restart: unless-stopped
networks:
  default:
    external: true
```

I just connected to the instance and launched test ball. Alt-tabbed to check on wolfmanager and it still says:

<img width="1865" height="418" alt="Image" src="https://github.com/user-attachments/assets/a2b5329f-7116-4efd-abe6-c41895c645cf" />

**Comment by Hukuma1** [comment]
<img width="1844" height="345" alt="Image" src="https://github.com/user-attachments/assets/fd3fc5ac-4d1b-4a0e-9784-961d5d85467c" />

I don't know what I did besides clearing out my devices again (re-pairing), but it works now! So sorry for the issue opening. Keep up the great work!

**Comment by salty2011** [comment]
Hah lol all good glad it's working.

Still the fact that it happened and you needed to go through those steps is interesting. I'll keep note of this
